<?php
/** @package Rent::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AutoMap.php");

/**
 * AutoDAO provides object-oriented access to the auto table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Rent::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AutoDAO extends Phreezable
{
	/** @var int */
	public $Placa;

	/** @var int */
	public $Modelo;

	/** @var int */
	public $Fkmarca;

	/** @var int */
	public $FktipoAuto;

	/** @var int */
	public $Ano;

	/** @var int */
	public $Motor;

	/** @var int */
	public $Color;

	/** @var int */
	public $NroPuertas;

	/** @var int */
	public $Capacidad;

	/** @var int */
	public $PrecioPorDia;

	/** @var int */
	public $TipoCombustible;

	/** @var int */
	public $CapacidadCombustible;

	/** @var int */
	public $TipoCaja;

	/** @var int */
	public $Estado;

	/** @var blob */
	public $Foto;

	/** @var int */
	public $Fkempresa;



}
?>